#Add for Assignment4 
CROSS_COMPILE=
CC=gcc
#aarch64-none-linux-gnu-

all: writer.c 
#	${CROSS_COMPILE}gcc -o writer writer.c
	${CROSS_COMPILE}${CC} -o writer writer.c
#	$(CC) $(CFLAGS) $(INCLUDES) $(OBJS) -o $(TARGET) $(LDFLAGS)

#	gcc -o writer writer.c

clean: 
	rm -f *.o writer
	#	$(RM) writer
